Console.WriteLine("enter five numbers");
int i=Convert.ToInt16(Console.ReadLine());
int j=Convert.ToInt16(Console.ReadLine());
int k=Convert.ToInt16(Console.ReadLine());
int l=Convert.ToInt16(Console.ReadLine());
int m=Convert.ToInt16(Console.ReadLine());
int sum;
sum=(i+j+k+l+m);
Console.WriteLine(sum);
int Avg;
Avg=((i+j+k+l+m)/5);
Console.WriteLine(Avg);